#!/bin/sh

export default_2g='radio0'
export default_5g=''

# 97-iccm-general expects:
#   network.@device[0].name='br-lan'
#   network.lan.device='br-lan'
# These should typically be true of default OpenWRT, but if they aren't, fix them here.